using CineTrack.API.Models;
using MongoDB.Driver;

namespace CineTrack.API.Services;

public class DataSeeder
{
    private readonly IMongoCollection<CatalogItem> _catalog;
    private readonly JikanService _jikan;
    private const string TmdbBase = "https://image.tmdb.org/t/p/w500";
    private const string TmdbBackdrop = "https://image.tmdb.org/t/p/w1280";

    // MAL IDs para buscar posters corretos via Jikan API
    private static readonly Dictionary<string, int> AnimeMalIds = new(StringComparer.OrdinalIgnoreCase)
    {
        ["Attack on Titan"] = 16498,
        ["Fullmetal Alchemist: Brotherhood"] = 5114,
        ["Death Note"] = 1535,
        ["Demon Slayer"] = 38000,
        ["Hunter x Hunter"] = 11061,
        ["My Hero Academia"] = 31964,
        ["Steins;Gate"] = 9253,
        ["Code Geass"] = 2053,
        ["One Punch Man"] = 21087,
        ["Neon Genesis Evangelion"] = 30,
        ["Vinland Saga"] = 37521,
        ["Jujutsu Kaisen"] = 40748,
        ["Spy x Family"] = 50265,
        ["Chainsaw Man"] = 44511,
        ["Cowboy Bebop"] = 1,
        ["Naruto: Shippuden"] = 1735,
        ["Dragon Ball Z"] = 813,
        ["One Piece"] = 21,
        ["Sword Art Online"] = 11757,
        ["Tokyo Ghoul"] = 20605,
        ["Mob Psycho 100"] = 32182,
        ["Re:Zero − Starting Life in Another World"] = 31240,
        ["Violet Evergarden"] = 37987,
        ["Made in Abyss"] = 34599,
        ["Parasyte: The Maxim"] = 27377,
        ["Haikyuu!!"] = 20583,
        ["Your Lie in April"] = 20665,
        ["Mushoku Tensei: Jobless Reincarnation"] = 46130,
        ["Overlord"] = 30326,
        ["Frieren: Beyond Journey's End"] = 52991,
    };

    public DataSeeder(MongoDbService mongoDb, JikanService jikan)
    {
        _catalog = mongoDb.GetCollection<CatalogItem>("catalog");
        _jikan = jikan;
    }

    /// <summary>Popula o catálogo global (todos os usuários veem).</summary>
    public async Task<int> SeedAsync(bool force = false)
    {
        if (force)
            await _catalog.DeleteManyAsync(FilterDefinition<CatalogItem>.Empty);
        else if (await _catalog.CountDocumentsAsync(FilterDefinition<CatalogItem>.Empty) > 0)
            return 0;

        var items = await BuildCatalogAsync();
        if (items.Count > 0)
            await _catalog.InsertManyAsync(items);
        return items.Count;
    }

    private async Task<List<CatalogItem>> BuildCatalogAsync()
    {
        var list = new List<CatalogItem>();

        // ─────────────────────────────────────────
        // MOVIES
        // ─────────────────────────────────────────
        list.AddRange(new[]
        {
            CatalogMovie("The Shawshank Redemption", 1994, 9.3,
                ["Drama"],
                $"{TmdbBase}/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
                "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", 142,
                backdrop: $"{TmdbBackdrop}/kXfqcdQKsToO0OUXHcrrNCHDBaR.jpg",
                director: "Frank Darabont",
                writers: ["Frank Darabont", "Stephen King"],
                studio: "Castle Rock Entertainment",
                cast: [CM("Tim Robbins","Andy Dufresne"), CM("Morgan Freeman","Ellis Boyd 'Red' Redding"), CM("Bob Gunton","Warden Norton"), CM("William Sadler","Heywood"), CM("Clancy Brown","Captain Hadley")],
                trailerUrl: "6hB3S9bIaco"),

            CatalogMovie( "The Godfather", 1972, 9.2,
                ["Crime", "Drama"],
                $"{TmdbBase}/3bhkrj58Vtu7enYsLegHnDmni3Q.jpg",
                "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", 175,
                backdrop: $"{TmdbBackdrop}/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
                director: "Francis Ford Coppola",
                writers: ["Mario Puzo", "Francis Ford Coppola"],
                studio: "Paramount Pictures",
                cast: [CM("Marlon Brando","Vito Corleone"), CM("Al Pacino","Michael Corleone"), CM("James Caan","Sonny Corleone"), CM("Robert Duvall","Tom Hagen"), CM("Diane Keaton","Kay Adams")],
                trailerUrl: "sY1S34973zA"),

            CatalogMovie( "The Dark Knight", 2008, 9.0,
                ["Action", "Crime", "Drama"],
                $"{TmdbBase}/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.", 152,
                backdrop: $"{TmdbBackdrop}/nMKdUFyrkirBBii99p2ygbsV4n4.jpg",
                director: "Christopher Nolan",
                writers: ["Jonathan Nolan", "Christopher Nolan"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Christian Bale","Bruce Wayne / Batman"), CM("Heath Ledger","The Joker"), CM("Aaron Eckhart","Harvey Dent"), CM("Michael Caine","Alfred"), CM("Gary Oldman","Commissioner Gordon")],
                trailerUrl: "EXeTwQWrcwY"),

            CatalogMovie( "Pulp Fiction", 1994, 8.9,
                ["Crime", "Drama"],
                $"{TmdbBase}/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
                "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", 154,
                backdrop: $"{TmdbBackdrop}/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
                director: "Quentin Tarantino",
                writers: ["Quentin Tarantino", "Roger Avary"],
                studio: "Miramax Films",
                cast: [CM("John Travolta","Vincent Vega"), CM("Uma Thurman","Mia Wallace"), CM("Samuel L. Jackson","Jules Winnfield"), CM("Harvey Keitel","The Wolf"), CM("Tim Roth","Pumpkin")],
                trailerUrl: "s7EdQ4FqbhY"),

            CatalogMovie( "Inception", 2010, 8.8,
                ["Action", "Sci-Fi", "Thriller"],
                $"{TmdbBase}/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
                "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.", 148,
                backdrop: $"{TmdbBackdrop}/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
                director: "Christopher Nolan",
                writers: ["Christopher Nolan"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Leonardo DiCaprio","Cobb"), CM("Joseph Gordon-Levitt","Arthur"), CM("Elliot Page","Ariadne"), CM("Tom Hardy","Eames"), CM("Ken Watanabe","Saito")],
                trailerUrl: "YoHD9XEInc0"),

            CatalogMovie( "Interstellar", 2014, 8.7,
                ["Adventure", "Drama", "Sci-Fi"],
                $"{TmdbBase}/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", 169,
                backdrop: $"{TmdbBackdrop}/pbrkL804c8yAv3zBZR4QPEafpAR.jpg",
                director: "Christopher Nolan",
                writers: ["Jonathan Nolan", "Christopher Nolan"],
                studio: "Paramount Pictures",
                cast: [CM("Matthew McConaughey","Cooper"), CM("Anne Hathaway","Brand"), CM("Jessica Chastain","Murph"), CM("Michael Caine","Professor Brand"), CM("Matt Damon","Mann")],
                trailerUrl: "zSWdZVtXT7E"),

            CatalogMovie( "The Matrix", 1999, 8.7,
                ["Action", "Sci-Fi"],
                $"{TmdbBase}/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
                "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", 136,
                backdrop: $"{TmdbBackdrop}/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
                director: "Lana Wachowski, Lilly Wachowski",
                writers: ["Lana Wachowski", "Lilly Wachowski"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Keanu Reeves","Neo"), CM("Laurence Fishburne","Morpheus"), CM("Carrie-Anne Moss","Trinity"), CM("Hugo Weaving","Agent Smith"), CM("Joe Pantoliano","Cypher")],
                trailerUrl: "vKQi3bBA1y8"),

            CatalogMovie( "Goodfellas", 1990, 8.7,
                ["Biography", "Crime", "Drama"],
                $"{TmdbBase}/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg",
                "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito.", 146,
                backdrop: $"{TmdbBackdrop}/sw7mordbZxgITU877yTpZCud90M.jpg",
                director: "Martin Scorsese",
                writers: ["Nicholas Pileggi", "Martin Scorsese"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Ray Liotta","Henry Hill"), CM("Robert De Niro","Jimmy Conway"), CM("Joe Pesci","Tommy DeVito"), CM("Lorraine Bracco","Karen Hill"), CM("Paul Sorvino","Paul Cicero")],
                trailerUrl: "2W13ext26kQ"),

            CatalogMovie( "Fight Club", 1999, 8.8,
                ["Drama", "Thriller"],
                $"{TmdbBase}/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
                "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.", 139,
                backdrop: $"{TmdbBackdrop}/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg",
                director: "David Fincher",
                writers: ["Jim Uhls", "Chuck Palahniuk"],
                studio: "20th Century Fox",
                cast: [CM("Brad Pitt","Tyler Durden"), CM("Edward Norton","The Narrator"), CM("Helena Bonham Carter","Marla Singer"), CM("Meat Loaf","Robert 'Bob' Paulson"), CM("Jared Leto","Angel Face")],
                trailerUrl: "SUXWAEX2jlg"),

            CatalogMovie( "Schindler's List", 1993, 9.0,
                ["Biography", "Drama", "History"],
                $"{TmdbBase}/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
                "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution.", 195,
                backdrop: $"{TmdbBackdrop}/loRmRzQXZeqG78TqZEgjHOkiKDc.jpg",
                director: "Steven Spielberg",
                writers: ["Steven Zaillian", "Thomas Keneally"],
                studio: "Universal Pictures",
                cast: [CM("Liam Neeson","Oskar Schindler"), CM("Ben Kingsley","Itzhak Stern"), CM("Ralph Fiennes","Amon Göth"), CM("Caroline Goodall","Emilie Schindler"), CM("Jonathan Sagall","Poldek Pfefferberg")],
                trailerUrl: "gG22ZEkWpKs"),

            CatalogMovie( "Parasite", 2019, 8.5,
                ["Comedy", "Drama", "Thriller"],
                $"{TmdbBase}/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", 132,
                backdrop: $"{TmdbBackdrop}/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
                director: "Bong Joon-ho",
                writers: ["Bong Joon-ho", "Han Jin-won"],
                studio: "CJ Entertainment",
                cast: [CM("Song Kang-ho","Ki-taek"), CM("Lee Sun-kyun","Mr. Park Dong-ik"), CM("Cho Yeo-jeong","Mrs. Park Yeon-kyo"), CM("Choi Woo-sik","Ki-woo"), CM("Park So-dam","Ki-jung")],
                trailerUrl: "5xH0HfJHsaY"),

            CatalogMovie( "Oppenheimer", 2023, 8.4,
                ["Biography", "Drama", "History"],
                $"{TmdbBase}/8Gxv8giaFIzmzdgSN31oOB55mRg.jpg",
                "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", 180,
                backdrop: $"{TmdbBackdrop}/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
                director: "Christopher Nolan",
                writers: ["Christopher Nolan"],
                studio: "Universal Pictures",
                cast: [CM("Cillian Murphy","J. Robert Oppenheimer"), CM("Emily Blunt","Katherine Oppenheimer"), CM("Matt Damon","Leslie Groves"), CM("Robert Downey Jr.","Lewis Strauss"), CM("Florence Pugh","Jean Tatlock")],
                trailerUrl: "uYPbbksJxIg"),

            CatalogMovie( "Dune", 2021, 8.0,
                ["Adventure", "Drama", "Sci-Fi"],
                $"{TmdbBase}/d5NXSklpcvJ0WhQl1uf3b1K6amX.jpg",
                "Feature adaptation of Frank Herbert's science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset in the galaxy.", 155,
                backdrop: $"{TmdbBackdrop}/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
                director: "Denis Villeneuve",
                writers: ["Jon Spaihts", "Denis Villeneuve", "Eric Roth"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Timothée Chalamet","Paul Atreides"), CM("Rebecca Ferguson","Lady Jessica Atreides"), CM("Zendaya","Chani"), CM("Oscar Isaac","Duke Leto Atreides"), CM("Josh Brolin","Gurney Halleck")],
                trailerUrl: "n9xhJrPXop4"),

            CatalogMovie( "Joker", 2019, 8.4,
                ["Crime", "Drama", "Thriller"],
                $"{TmdbBase}/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
                "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.", 122,
                backdrop: $"{TmdbBackdrop}/n6bUvigpRFqSwmPp1m2YADwqkay.jpg",
                director: "Todd Phillips",
                writers: ["Todd Phillips", "Scott Silver"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Joaquin Phoenix","Arthur Fleck / Joker"), CM("Robert De Niro","Murray Franklin"), CM("Zazie Beetz","Sophie Dumond"), CM("Frances Conroy","Penny Fleck"), CM("Brett Cullen","Thomas Wayne")],
                trailerUrl: "zAGVQLHvwOY"),

            CatalogMovie( "The Silence of the Lambs", 1991, 8.6,
                ["Crime", "Drama", "Thriller"],
                $"{TmdbBase}/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
                "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.", 118,
                backdrop: null,
                director: "Jonathan Demme",
                writers: ["Ted Tally", "Thomas Harris"],
                studio: "Orion Pictures",
                cast: [CM("Jodie Foster","Clarice Starling"), CM("Anthony Hopkins","Dr. Hannibal Lecter"), CM("Scott Glenn","Jack Crawford"), CM("Ted Levine","Buffalo Bill"), CM("Anthony Heald","Dr. Chilton")],
                trailerUrl: "RuX2MhwVTEA"),

            CatalogMovie( "Gladiator", 2000, 8.5,
                ["Action", "Adventure", "Drama"],
                $"{TmdbBase}/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
                "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.", 155,
                backdrop: $"{TmdbBackdrop}/6WBIzCgmDCYrqh64yDREGeDk9d3.jpg",
                director: "Ridley Scott",
                writers: ["David Franzoni", "John Logan", "William Nicholson"],
                studio: "DreamWorks Pictures",
                cast: [CM("Russell Crowe","Maximus Decimus Meridius"), CM("Joaquin Phoenix","Commodus"), CM("Connie Nielsen","Lucilla"), CM("Oliver Reed","Proximo"), CM("Derek Jacobi","Gracchus")],
                trailerUrl: "owK1qxDselE"),

            CatalogMovie( "The Lord of the Rings: The Fellowship of the Ring", 2001, 8.8,
                ["Adventure", "Fantasy"],
                $"{TmdbBase}/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
                "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth.", 178,
                backdrop: $"{TmdbBackdrop}/pIgZStv8aiS9od1DDrxHysCMRXx.jpg",
                director: "Peter Jackson",
                writers: ["Fran Walsh", "Philippa Boyens", "Peter Jackson"],
                studio: "New Line Cinema",
                cast: [CM("Elijah Wood","Frodo Baggins"), CM("Ian McKellen","Gandalf the Grey"), CM("Viggo Mortensen","Aragorn"), CM("Sean Bean","Boromir"), CM("Orlando Bloom","Legolas")],
                trailerUrl: "V75dMMIW2B4"),

            CatalogMovie( "Avengers: Endgame", 2019, 8.4,
                ["Action", "Adventure", "Sci-Fi"],
                $"{TmdbBase}/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
                "After the devastating events of Avengers: Infinity War, the universe is in ruins. The Avengers assemble once more to reverse Thanos's actions.", 181,
                backdrop: $"{TmdbBackdrop}/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
                director: "Anthony and Joe Russo",
                writers: ["Christopher Markus", "Stephen McFeely"],
                studio: "Marvel Studios",
                cast: [CM("Robert Downey Jr.","Tony Stark / Iron Man"), CM("Chris Evans","Steve Rogers / Captain America"), CM("Mark Ruffalo","Bruce Banner / Hulk"), CM("Chris Hemsworth","Thor"), CM("Scarlett Johansson","Natasha Romanoff")],
                trailerUrl: "TcMBFSGVi1c"),

            CatalogMovie( "Spider-Man: No Way Home", 2021, 8.3,
                ["Action", "Adventure", "Fantasy"],
                $"{TmdbBase}/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
                "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.", 148,
                backdrop: $"{TmdbBackdrop}/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
                director: "Jon Watts",
                writers: ["Chris McKenna", "Erik Sommers"],
                studio: "Columbia Pictures",
                cast: [CM("Tom Holland","Peter Parker / Spider-Man"), CM("Zendaya","MJ"), CM("Benedict Cumberbatch","Doctor Strange"), CM("Jacob Batalon","Ned Leeds"), CM("Jamie Foxx","Electro")],
                trailerUrl: "JfVOs4VSpmA"),

            CatalogMovie( "Everything Everywhere All at Once", 2022, 7.8,
                ["Action", "Adventure", "Comedy"],
                $"{TmdbBase}/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
                "A middle-aged Chinese immigrant is swept up into an insane adventure where she alone can save existence by exploring other universes.", 139,
                backdrop: $"{TmdbBackdrop}/fePczipEG7EFCFPgolDVdoFMzDw.jpg",
                director: "Daniel Kwan & Daniel Scheinert",
                writers: ["Daniel Kwan", "Daniel Scheinert"],
                studio: "A24",
                cast: [CM("Michelle Yeoh","Evelyn Wang"), CM("Ke Huy Quan","Waymond Wang"), CM("Jamie Lee Curtis","Deirdre Beaubeirdre"), CM("Stephanie Hsu","Joy Wang / Jobu Tupaki"), CM("James Hong","Gong Gong")],
                trailerUrl: "wxN1T1uxQ2g"),

            CatalogMovie( "Se7en", 1995, 8.6,
                ["Crime", "Drama", "Mystery"],
                $"{TmdbBase}/6yoghtyTpznpBik8EngEmJskVnS.jpg",
                "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.", 127,
                backdrop: $"{TmdbBackdrop}/3Cz7ySOQJmqiuTi7zvNkRnFxGkQ.jpg",
                director: "David Fincher",
                writers: ["Andrew Kevin Walker"],
                studio: "New Line Cinema",
                cast: [CM("Brad Pitt","Detective David Mills"), CM("Morgan Freeman","Detective Lt. Somerset"), CM("Kevin Spacey","John Doe"), CM("Gwyneth Paltrow","Tracy Mills"), CM("R. Lee Ermey","Police Captain")],
                trailerUrl: "znmZoVkCjpI"),

            CatalogMovie( "The Shining", 1980, 8.4,
                ["Drama", "Horror"],
                $"{TmdbBase}/b6ko0IKC8MdYBBPkkA1aBPLe2yz.jpg",
                "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.", 146,
                backdrop: null,
                director: "Stanley Kubrick",
                writers: ["Stanley Kubrick", "Diane Johnson"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Jack Nicholson","Jack Torrance"), CM("Shelley Duvall","Wendy Torrance"), CM("Danny Lloyd","Danny Torrance"), CM("Scatman Crothers","Dick Hallorann"), CM("Barry Nelson","Stuart Ullman")],
                trailerUrl: "S014oGZiSdI"),

            CatalogMovie( "Alien", 1979, 8.5,
                ["Horror", "Sci-Fi"],
                $"{TmdbBase}/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg",
                "The crew of a commercial spacecraft encounters a deadly extraterrestrial creature.", 117,
                backdrop: null,
                director: "Ridley Scott",
                writers: ["Dan O'Bannon", "Ronald Shusett"],
                studio: "20th Century Fox",
                cast: [CM("Sigourney Weaver","Ellen Ripley"), CM("Tom Skerritt","Arthur Dallas"), CM("John Hurt","Gilbert 'Kane' Kane"), CM("Ian Holm","Ash"), CM("Harry Dean Stanton","Brett")],
                trailerUrl: "LjLamj-b0I8"),

            CatalogMovie( "Blade Runner 2049", 2017, 8.0,
                ["Drama", "Mystery", "Sci-Fi"],
                $"{TmdbBase}/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
                "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard.", 164,
                backdrop: null,
                director: "Denis Villeneuve",
                writers: ["Hampton Fancher", "Michael Green"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Ryan Gosling","K"), CM("Harrison Ford","Rick Deckard"), CM("Ana de Armas","Joi"), CM("Sylvia Hoeks","Luv"), CM("Robin Wright","Lieutenant Joshi")],
                trailerUrl: "gCcx85zbxz4"),

            CatalogMovie( "Mad Max: Fury Road", 2015, 8.1,
                ["Action", "Adventure", "Sci-Fi"],
                $"{TmdbBase}/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
                "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners.", 120,
                backdrop: $"{TmdbBackdrop}/phszHPFnhCCn4D2cIHJINHKMnCq.jpg",
                director: "George Miller",
                writers: ["George Miller", "Brendan McCarthy", "Nick Lathouris"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Tom Hardy","Max Rockatansky"), CM("Charlize Theron","Imperator Furiosa"), CM("Nicholas Hoult","Nux"), CM("Hugh Keays-Byrne","Immortan Joe"), CM("Josh Helman","Slit")],
                trailerUrl: "hEJnMQG9ev8"),

            CatalogMovie( "The Prestige", 2006, 8.5,
                ["Drama", "Mystery", "Sci-Fi"],
                $"{TmdbBase}/bdN3gXuIZYaJDFSCiD2jzBUPQAp.jpg",
                "After a tragic accident, two stage magicians engage in a fierce battle to create the ultimate illusion while each sacrifices everything they have to outwit the other.", 130,
                backdrop: null,
                director: "Christopher Nolan",
                writers: ["Jonathan Nolan", "Christopher Nolan"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Christian Bale","Alfred Borden"), CM("Hugh Jackman","Robert Angier"), CM("Scarlett Johansson","Olivia Wenscombe"), CM("Michael Caine","Cutter"), CM("Rebecca Hall","Sarah")],
                trailerUrl: "o4gHCmTQDVI"),

            CatalogMovie( "No Country for Old Men", 2007, 8.2,
                ["Crime", "Drama", "Thriller"],
                $"{TmdbBase}/9HEBs09iF7KHhKp1NtQJEJJKKmJ.jpg",
                "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and over two million dollars in cash near the Rio Grande.", 122,
                backdrop: null,
                director: "Joel Coen & Ethan Coen",
                writers: ["Joel Coen", "Ethan Coen"],
                studio: "Miramax Films",
                cast: [CM("Tommy Lee Jones","Sheriff Ed Tom Bell"), CM("Javier Bardem","Anton Chigurh"), CM("Josh Brolin","Llewelyn Moss"), CM("Woody Harrelson","Carson Wells"), CM("Kelly Macdonald","Carla Jean Moss")],
                trailerUrl: "38A__WT3-o0"),

            CatalogMovie( "Forrest Gump", 1994, 8.8,
                ["Comedy", "Drama", "Romance"],
                $"{TmdbBase}/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
                "The presidencies of Kennedy and Johnson, Vietnam, Watergate and other history unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.", 142,
                backdrop: $"{TmdbBackdrop}/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg",
                director: "Robert Zemeckis",
                writers: ["Eric Roth", "Winston Groom"],
                studio: "Paramount Pictures",
                cast: [CM("Tom Hanks","Forrest Gump"), CM("Robin Wright","Jenny Curran"), CM("Gary Sinise","Lt. Dan Taylor"), CM("Mykelti Williamson","Bubba Blue"), CM("Sally Field","Mrs. Gump")],
                trailerUrl: "bLvqoHBptjg"),

            CatalogMovie( "The Green Mile", 1999, 8.6,
                ["Crime", "Drama", "Fantasy"],
                $"{TmdbBase}/uXDfjJbdP4ijW5hWSBrPl9KcertP.jpg",
                "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape who has a mysterious gift.", 189,
                backdrop: null,
                director: "Frank Darabont",
                writers: ["Frank Darabont", "Stephen King"],
                studio: "Castle Rock Entertainment",
                cast: [CM("Tom Hanks","Paul Edgecomb"), CM("Michael Clarke Duncan","John Coffey"), CM("David Morse","Brutus 'Brutal' Howell"), CM("James Cromwell","Warden Hal Moores"), CM("Michael Jeter","Eduard Delacroix")],
                trailerUrl: "Ki4haFTeC0I"),

            CatalogMovie( "The Departed", 2006, 8.5,
                ["Crime", "Drama", "Thriller"],
                $"{TmdbBase}/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
                "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.", 151,
                backdrop: $"{TmdbBackdrop}/8Od5zV7Q7zNOX0y9tyNgpTmoiGA.jpg",
                director: "Martin Scorsese",
                writers: ["William Monahan"],
                studio: "Warner Bros. Pictures",
                cast: [CM("Leonardo DiCaprio","Billy Costigan"), CM("Matt Damon","Colin Sullivan"), CM("Jack Nicholson","Frank Costello"), CM("Mark Wahlberg","Dignam"), CM("Martin Sheen","Captain Queenan")],
                trailerUrl: "auGNBFkuZnI"),

            CatalogMovie( "Django Unchained", 2012, 8.4,
                ["Drama", "Western"],
                $"{TmdbBase}/7oWY8VDWW7thTzWh3OKYRkWcKBa.jpg",
                "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.", 165,
                backdrop: null,
                director: "Quentin Tarantino",
                writers: ["Quentin Tarantino"],
                studio: "Columbia Pictures",
                cast: [CM("Jamie Foxx","Django Freeman"), CM("Christoph Waltz","Dr. King Schultz"), CM("Leonardo DiCaprio","Calvin Candie"), CM("Kerry Washington","Broomhilda von Shaft"), CM("Samuel L. Jackson","Stephen")],
                trailerUrl: "eUdM9vrCbow"),

            CatalogMovie( "The Wolf of Wall Street", 2013, 8.2,
                ["Biography", "Comedy", "Crime"],
                $"{TmdbBase}/34m2tygAYBGqA9MXKhRDtzYd4Ye.jpg",
                "Based on the true story of Jordan Belfort, from his rise to a wealthy stockbroker living the high life to his fall involving crime, corruption and the federal government.", 180,
                backdrop: null,
                director: "Martin Scorsese",
                writers: ["Terence Winter", "Jordan Belfort"],
                studio: "Paramount Pictures",
                cast: [CM("Leonardo DiCaprio","Jordan Belfort"), CM("Jonah Hill","Donnie Azoff"), CM("Margot Robbie","Naomi Lapaglia"), CM("Matthew McConaughey","Mark Hanna"), CM("Kyle Chandler","Patrick Denham")],
                trailerUrl: "iszwuX1AK6A"),

            CatalogMovie( "Whiplash", 2014, 8.5,
                ["Drama", "Music"],
                $"{TmdbBase}/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
                "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.", 107,
                backdrop: null,
                director: "Damien Chazelle",
                writers: ["Damien Chazelle"],
                studio: "Sony Pictures Classics",
                cast: [CM("Miles Teller","Andrew Neiman"), CM("J.K. Simmons","Terence Fletcher"), CM("Melissa Benoist","Nicole"), CM("Paul Reiser","Jim Neiman"), CM("Austin Stowell","Ryan")],
                trailerUrl: "7d_jQycdQGo"),

            CatalogMovie( "La La Land", 2016, 8.0,
                ["Comedy", "Drama", "Music"],
                $"{TmdbBase}/uDO8zWDhfWwoFdKS4fzkUJt0Bs0.jpg",
                "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.", 128,
                backdrop: null,
                director: "Damien Chazelle",
                writers: ["Damien Chazelle"],
                studio: "Summit Entertainment",
                cast: [CM("Ryan Gosling","Sebastian Wilder"), CM("Emma Stone","Mia Dolan"), CM("John Legend","Keith"), CM("Rosemarie DeWitt","Laura Wilder"), CM("J.K. Simmons","Bill")],
                trailerUrl: "0pdqf4P9MB8"),

            CatalogMovie( "1917", 2019, 8.3,
                ["Action", "Drama", "War"],
                $"{TmdbBase}/iZf0KyrE25z1sage4SYQLAsbqdP.jpg",
                "Two soldiers are assigned to race against time to deliver a message that will stop 1,600 men from walking straight into a deadly trap during World War I.", 119,
                backdrop: null,
                director: "Sam Mendes",
                writers: ["Sam Mendes", "Krysty Wilson-Cairns"],
                studio: "Universal Pictures",
                cast: [CM("George MacKay","Schofield"), CM("Dean-Charles Chapman","Blake"), CM("Mark Strong","Captain Smith"), CM("Andrew Scott","Lieutenant Leslie"), CM("Richard Madden","Lieutenant Blake")],
                trailerUrl: "YqNYrYUiMfg"),

            CatalogMovie( "The Revenant", 2015, 8.0,
                ["Action", "Adventure", "Drama"],
                $"{TmdbBase}/ji3ecJphATlVgV8plR4sJ7sJ7ask.jpg",
                "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.", 156,
                backdrop: null,
                director: "Alejandro González Iñárritu",
                writers: ["Mark L. Smith", "Alejandro González Iñárritu"],
                studio: "20th Century Fox",
                cast: [CM("Leonardo DiCaprio","Hugh Glass"), CM("Tom Hardy","John Fitzgerald"), CM("Will Poulter","Jim Bridger"), CM("Domhnall Gleeson","Captain Henry"), CM("Forrest Goodluck","Hawk")],
                trailerUrl: "LoebZZ8K5N0"),

            CatalogMovie( "Get Out", 2017, 7.7,
                ["Horror", "Mystery", "Thriller"],
                $"{TmdbBase}/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
                "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point.", 104,
                backdrop: null,
                director: "Jordan Peele",
                writers: ["Jordan Peele"],
                studio: "Universal Pictures",
                cast: [CM("Daniel Kaluuya","Chris Washington"), CM("Allison Williams","Rose Armitage"), CM("Catherine Keener","Missy Armitage"), CM("Bradley Whitford","Dean Armitage"), CM("Lil Rel Howery","Rod Williams")],
                trailerUrl: "sRfnevzM9kQ"),

            CatalogMovie( "A Beautiful Mind", 2001, 8.2,
                ["Biography", "Drama"],
                $"{TmdbBase}/zwzWCmH72OSC9NA0ipoqyjdgMOb.jpg",
                "After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.", 135,
                backdrop: null,
                director: "Ron Howard",
                writers: ["Akiva Goldsman", "Sylvia Nasar"],
                studio: "Universal Pictures",
                cast: [CM("Russell Crowe","John Nash"), CM("Ed Harris","William Parcher"), CM("Jennifer Connelly","Alicia Nash"), CM("Paul Bettany","Charles Herman"), CM("Adam Goldberg","Sol")],
                trailerUrl: "YWwAOutgWBQ"),

            CatalogMovie( "Tenet", 2020, 7.3,
                ["Action", "Sci-Fi", "Thriller"],
                $"{TmdbBase}/k68nPLbIST6NP96JmTxmZijZchr.jpg",
                "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage on a mission that unfolds beyond real time.", 150,
                backdrop: null,
                director: "Christopher Nolan",
                writers: ["Christopher Nolan"],
                studio: "Warner Bros. Pictures",
                cast: [CM("John David Washington","The Protagonist"), CM("Robert Pattinson","Neil"), CM("Elizabeth Debicki","Kat"), CM("Dimple Kapadia","Priya Singh"), CM("Kenneth Branagh","Andrei Sator")],
                trailerUrl: "LdOM0x0XDMo"),

            CatalogMovie( "Memento", 2000, 8.4,
                ["Mystery", "Thriller"],
                $"{TmdbBase}/yuNs09hvpHVU1cWRjOoC6niwhJg.jpg",
                "A man with short-term memory loss attempts to track down his wife's murderer using photographs and notes tattooed on his body.", 113,
                backdrop: null,
                director: "Christopher Nolan",
                writers: ["Christopher Nolan", "Jonathan Nolan"],
                studio: "Summit Entertainment",
                cast: [CM("Guy Pearce","Leonard Shelby"), CM("Carrie-Anne Moss","Natalie"), CM("Joe Pantoliano","Teddy"), CM("Mark Boone Junior","Burt"), CM("Jorja Fox","Leonard's Wife")],
                trailerUrl: "0vS0E9ZtT_Y"),
        });

        // ─────────────────────────────────────────
        // SERIES
        // ─────────────────────────────────────────
        list.AddRange(new[]
        {
            CatalogSeries( "Breaking Bad", 2008, 9.5,
                ["Crime", "Drama", "Thriller"],
                $"{TmdbBase}/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
                "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine.", 62,
                backdrop: $"{TmdbBackdrop}/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
                director: "Vince Gilligan",
                writers: ["Vince Gilligan"],
                studio: "AMC Studios",
                cast: [CM("Bryan Cranston","Walter White"), CM("Aaron Paul","Jesse Pinkman"), CM("Anna Gunn","Skyler White"), CM("Dean Norris","Hank Schrader"), CM("Bob Odenkirk","Saul Goodman")],
                trailerUrl: "HhesaQXLuRY"),

            CatalogSeries( "Game of Thrones", 2011, 9.3,
                ["Action", "Adventure", "Drama"],
                $"{TmdbBase}/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
                "Nine noble families fight for control over the mythical lands of Westeros, while an ancient enemy returns after a long period of dormancy.", 73,
                backdrop: $"{TmdbBackdrop}/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
                director: "David Benioff & D.B. Weiss",
                writers: ["David Benioff", "D.B. Weiss"],
                studio: "HBO",
                cast: [CM("Emilia Clarke","Daenerys Targaryen"), CM("Peter Dinklage","Tyrion Lannister"), CM("Kit Harington","Jon Snow"), CM("Lena Headey","Cersei Lannister"), CM("Sophie Turner","Sansa Stark")],
                trailerUrl: "bjqx54BMzSY"),

            CatalogSeries( "Chernobyl", 2019, 9.4,
                ["Drama", "History", "Thriller"],
                $"{TmdbBase}/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
                "A dramatization of the catastrophic nuclear accident at Chernobyl, the cleanup efforts and government cover-up.", 5,
                backdrop: null,
                director: "Craig Mazin",
                writers: ["Craig Mazin"],
                studio: "HBO",
                cast: [CM("Jared Harris","Valery Legasov"), CM("Stellan Skarsgård","Boris Shcherbina"), CM("Emily Watson","Ulyana Khomyuk"), CM("Paul Ritter","Anatoly Dyatlov"), CM("Sam Troughton","Alexander Akimov")],
                trailerUrl: "s9APLXM9Ei8"),

            CatalogSeries( "Stranger Things", 2016, 8.7,
                ["Drama", "Fantasy", "Horror"],
                $"{TmdbBase}/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
                "When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.", 42,
                backdrop: $"{TmdbBackdrop}/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
                director: "Matt & Ross Duffer",
                writers: ["Matt Duffer", "Ross Duffer"],
                studio: "Netflix",
                cast: [CM("Winona Ryder","Joyce Byers"), CM("David Harbour","Jim Hopper"), CM("Millie Bobby Brown","Eleven"), CM("Finn Wolfhard","Mike Wheeler"), CM("Gaten Matarazzo","Dustin Henderson")],
                trailerUrl: "b9EkMc79ZSU"),

            CatalogSeries( "The Sopranos", 1999, 9.2,
                ["Crime", "Drama"],
                $"{TmdbBase}/57okJJUBK0AaijxHp9HzPSVFPkM.jpg",
                "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life.", 86,
                backdrop: null,
                director: "David Chase",
                writers: ["David Chase"],
                studio: "HBO",
                cast: [CM("James Gandolfini","Tony Soprano"), CM("Lorraine Bracco","Dr. Jennifer Melfi"), CM("Edie Falco","Carmela Soprano"), CM("Michael Imperioli","Christopher Moltisanti"), CM("Dominic Chianese","Junior Soprano")],
                trailerUrl: "KVnOjCMv6d4"),

            CatalogSeries( "Succession", 2018, 8.9,
                ["Drama"],
                $"{TmdbBase}/e2X8x0KHDHBEGXvFqNJOq5XrFSR.jpg",
                "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down.", 39,
                backdrop: null,
                director: "Jesse Armstrong",
                writers: ["Jesse Armstrong"],
                studio: "HBO",
                cast: [CM("Brian Cox","Logan Roy"), CM("Jeremy Strong","Kendall Roy"), CM("Sarah Snook","Siobhan Roy"), CM("Kieran Culkin","Roman Roy"), CM("Matthew Macfadyen","Tom Wambsgans")],
                trailerUrl: "OzYxJV_rmE8"),

            CatalogSeries( "True Detective", 2014, 9.0,
                ["Crime", "Drama", "Mystery"],
                $"{TmdbBase}/lchxx1NeeCbFUrSjKxKSBhLhxqX.jpg",
                "An anthology series in which a brutal crime in Louisiana, Texas and the Ozarks is investigated by two detectives across several years.", 38,
                backdrop: null,
                director: "Nic Pizzolatto",
                writers: ["Nic Pizzolatto"],
                studio: "HBO",
                cast: [CM("Matthew McConaughey","Rustin Cohle"), CM("Woody Harrelson","Martin Hart"), CM("Michelle Monaghan","Maggie Hart"), CM("Michael Potts","Det. Maynard Gilbough"), CM("Tory Kittles","Det. Thomas Papania")],
                trailerUrl: "_pHHG_0ByFE"),

            CatalogSeries( "Black Mirror", 2011, 8.8,
                ["Drama", "Sci-Fi", "Thriller"],
                $"{TmdbBase}/7PRddO7z7MCPi0yLpxnUXDjRXBH.jpg",
                "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.", 27,
                backdrop: null,
                director: "Charlie Brooker",
                writers: ["Charlie Brooker"],
                studio: "Channel 4 / Netflix",
                cast: [CM("Bryce Dallas Howard","Lacie — S03E01"), CM("Jon Hamm","Matt — S02E04"), CM("Daniel Kaluuya","Bing — S01E02"), CM("Jodie Whittaker","Victoria — S02E02")],
                trailerUrl: "jDiYGjDjMss"),

            CatalogSeries( "Dark", 2017, 8.8,
                ["Crime", "Drama", "Mystery"],
                $"{TmdbBase}/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
                "A family saga with a supernatural twist, set in a German town, where the disappearance of two young children exposes the relationships among four families.", 26,
                backdrop: null,
                director: "Baran bo Odar",
                writers: ["Baran bo Odar", "Jantje Friese"],
                studio: "Netflix",
                cast: [CM("Louis Hofmann","Jonas Kahnwald"), CM("Lisa Vicari","Martha Nielsen"), CM("Maja Schöne","Hannah Kahnwald"), CM("Karoline Eichhorn","Charlotte Doppler"), CM("Andreas Pietschmann","The Stranger")],
                trailerUrl: "rrwycJ08PSA"),

            CatalogSeries( "Arcane", 2021, 9.0,
                ["Animation", "Action", "Adventure"],
                $"{TmdbBase}/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
                "Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League of Legends champions.", 9,
                backdrop: null,
                director: "Christian Linke & Alex Yee",
                writers: ["Christian Linke", "Alex Yee"],
                studio: "Riot Games / Netflix",
                cast: [CM("Hailee Steinfeld","Vi"), CM("Ella Purnell","Jinx"), CM("Kevin Alejandro","Jayce"), CM("Katie Leung","Caitlyn"), CM("Jason Spisak","Silco")],
                trailerUrl: "fXmAurh012s"),

            CatalogSeries( "The Last of Us", 2023, 8.7,
                ["Action", "Adventure", "Drama"],
                $"{TmdbBase}/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
                "After a global catastrophe, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.", 9,
                backdrop: null,
                director: "Craig Mazin & Neil Druckmann",
                writers: ["Craig Mazin", "Neil Druckmann"],
                studio: "HBO",
                cast: [CM("Pedro Pascal","Joel Miller"), CM("Bella Ramsey","Ellie Williams"), CM("Anna Torv","Tess"), CM("Gabriel Luna","Tommy Miller"), CM("Merle Dandridge","Marlene")],
                trailerUrl: "uLtkt8BonwM"),

            CatalogSeries( "House of the Dragon", 2022, 8.4,
                ["Action", "Adventure", "Drama"],
                $"{TmdbBase}/z2yahl2uefxDCl0nogcRBstwruJ.jpg",
                "The story of House Targaryen, set 200 years before the events of Game of Thrones.", 20,
                backdrop: null,
                director: "Ryan Condal",
                writers: ["Ryan Condal", "George R.R. Martin"],
                studio: "HBO",
                cast: [CM("Paddy Considine","King Viserys I Targaryen"), CM("Matt Smith","Prince Daemon Targaryen"), CM("Olivia Cooke","Alicent Hightower"), CM("Emma D'Arcy","Princess Rhaenyra Targaryen"), CM("Eve Best","Princess Rhaenys Targaryen")],
                trailerUrl: "DotnJ7tTA34"),

            CatalogSeries( "Peaky Blinders", 2013, 8.8,
                ["Crime", "Drama"],
                $"{TmdbBase}/vUUqzWa2LnHIVqkaKVn3nyfVs15.jpg",
                "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps.", 36,
                backdrop: null,
                director: "Steven Knight",
                writers: ["Steven Knight"],
                studio: "BBC",
                cast: [CM("Cillian Murphy","Thomas 'Tommy' Shelby"), CM("Sam Neill","Inspector Chester Campbell"), CM("Helen McCrory","Polly Gray"), CM("Paul Anderson","Arthur Shelby"), CM("Joe Cole","John Shelby")],
                trailerUrl: "oVzVdvGIC7U"),

            CatalogSeries( "Money Heist", 2017, 8.3,
                ["Action", "Crime", "Mystery"],
                $"{TmdbBase}/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg",
                "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history.", 41,
                backdrop: null,
                director: "Álex Pina",
                writers: ["Álex Pina"],
                studio: "Netflix",
                cast: [CM("Úrsula Corberó","Tokyo"), CM("Álvaro Morte","The Professor"), CM("Itziar Ituño","Inspector Raquel Murillo"), CM("Miguel Herrán","Rio"), CM("Jaime Lorente","Denver")],
                trailerUrl: "_InqQJRqGW4"),

            CatalogSeries( "Squid Game", 2021, 8.0,
                ["Action", "Drama", "Mystery"],
                $"{TmdbBase}/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
                "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.", 9,
                backdrop: null,
                director: "Hwang Dong-hyuk",
                writers: ["Hwang Dong-hyuk"],
                studio: "Netflix",
                cast: [CM("Lee Jung-jae","Seong Gi-hun"), CM("Park Hae-soo","Cho Sang-woo"), CM("Wi Ha-joon","Hwang Jun-ho"), CM("HoYeon Jung","Kang Sae-byeok"), CM("O Yeong-su","Oh Il-nam")],
                trailerUrl: "oqxAJKy0ii4"),

            CatalogSeries( "Severance", 2022, 8.7,
                ["Drama", "Mystery", "Sci-Fi"],
                $"{TmdbBase}/lTxlmM7jLv3oq6VCHx2VDtbcYOF.jpg",
                "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives.", 19,
                backdrop: null,
                director: "Dan Erickson",
                writers: ["Dan Erickson"],
                studio: "Apple TV+",
                cast: [CM("Adam Scott","Mark Scout"), CM("Britt Lower","Helly R."), CM("Patricia Arquette","Harmony Cobel"), CM("John Turturro","Irving Bailiff"), CM("Christopher Walken","Burt Goodman")],
                trailerUrl: "xEQP4VVuyrY"),

            CatalogSeries( "Better Call Saul", 2015, 9.0,
                ["Crime", "Drama"],
                $"{TmdbBase}/faXT8V80JRhnArTAeYXz0ZwZnNp.jpg",
                "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.", 63,
                backdrop: null,
                director: "Vince Gilligan & Peter Gould",
                writers: ["Vince Gilligan", "Peter Gould"],
                studio: "AMC",
                cast: [CM("Bob Odenkirk","Jimmy McGill / Saul Goodman"), CM("Jonathan Banks","Mike Ehrmantraut"), CM("Rhea Seehorn","Kim Wexler"), CM("Patrick Fabian","Howard Hamlin"), CM("Michael Mando","Nacho Varga")],
                trailerUrl: "HN4oydykJFc"),

            CatalogSeries( "Mindhunter", 2017, 8.6,
                ["Crime", "Drama", "Thriller"],
                $"{TmdbBase}/neGQMNeo9L9YE4s4xpPt2hHlUvL.jpg",
                "In the late 1970s two FBI agents expand criminal science by delving into the psychology of murder.", 19,
                backdrop: null,
                director: "Joe Penhall",
                writers: ["Joe Penhall"],
                studio: "Netflix",
                cast: [CM("Jonathan Groff","Holden Ford"), CM("Holt McCallany","Bill Tench"), CM("Anna Torv","Dr. Wendy Carr"), CM("Hannah Gross","Debbie Mitford"), CM("Cotter Smith","Unit Chief Robert Shepard")],
                trailerUrl: "_pI7OCo3VeI"),

            CatalogSeries( "The Wire", 2002, 9.3,
                ["Crime", "Drama", "Thriller"],
                $"{TmdbBase}/4lbclFySvugI51fwsyxBTOm4DqK.jpg",
                "The drug scene in Baltimore, as seen through the eyes of drug dealers and law enforcement.", 60,
                backdrop: null,
                director: "David Simon",
                writers: ["David Simon"],
                studio: "HBO",
                cast: [CM("Dominic West","Jimmy McNulty"), CM("Lance Reddick","Cedric Daniels"), CM("Wood Harris","Avon Barksdale"), CM("Idris Elba","Stringer Bell"), CM("Sonja Sohn","Kima Greggs")],
                trailerUrl: "bkvSMtQnDgI"),

            CatalogSeries( "Westworld", 2016, 8.6,
                ["Drama", "Mystery", "Sci-Fi"],
                $"{TmdbBase}/8MfgyFHf7XEboZl7Ces4xmpNj6B.jpg",
                "Set at the intersection of the near future and the reimagined past, Westworld is a dark odyssey about the dawn of artificial consciousness.", 36,
                backdrop: null,
                director: "Jonathan Nolan & Lisa Joy",
                writers: ["Jonathan Nolan", "Lisa Joy"],
                studio: "HBO",
                cast: [CM("Evan Rachel Wood","Dolores Abernathy"), CM("Thandiwe Newton","Maeve Millay"), CM("Jeffrey Wright","Bernard Lowe"), CM("Anthony Hopkins","Dr. Robert Ford"), CM("Ed Harris","The Man in Black")],
                trailerUrl: "cBWn8BRkRjQ"),

            CatalogSeries( "The Boys", 2019, 8.7,
                ["Action", "Comedy", "Crime"],
                $"{TmdbBase}/stTEycfG9928HYGEISBFaG1ngjM.jpg",
                "A group of vigilantes known informally as 'The Boys' set out to take down corrupt superheroes who abuse their superpowers.", 32,
                backdrop: null,
                director: "Eric Kripke",
                writers: ["Eric Kripke"],
                studio: "Amazon Prime Video",
                cast: [CM("Karl Urban","Billy Butcher"), CM("Jack Quaid","Hughie Campbell"), CM("Antony Starr","Homelander"), CM("Erin Moriarty","Annie January / Starlight"), CM("Laz Alonso","Mother's Milk")],
                trailerUrl: "M1bhOaLV4EU"),

            CatalogSeries( "Euphoria", 2019, 8.4,
                ["Drama"],
                $"{TmdbBase}/3Q0hd3heuWwDWpwcDkhQOA6TYWI.jpg",
                "A look at life for a group of high school students as they grapple with issues of drugs, sex, and violence.", 16,
                backdrop: null,
                director: "Sam Levinson",
                writers: ["Sam Levinson"],
                studio: "HBO",
                cast: [CM("Zendaya","Rue Bennett"), CM("Hunter Schafer","Jules Vaughan"), CM("Sydney Sweeney","Cassie Howard"), CM("Jacob Elordi","Nate Jacobs"), CM("Maude Apatow","Lexi Howard")],
                trailerUrl: "9SBGWIaKmcQ"),

            CatalogSeries( "Ozark", 2017, 8.5,
                ["Crime", "Drama", "Thriller"],
                $"{TmdbBase}/pCGyPVrI9Fzw6rE1Pvi4BIXF0MK.jpg",
                "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.", 44,
                backdrop: null,
                director: "Bill Dubuque & Mark Williams",
                writers: ["Bill Dubuque", "Mark Williams"],
                studio: "Netflix",
                cast: [CM("Jason Bateman","Marty Byrde"), CM("Laura Linney","Wendy Byrde"), CM("Sofia Hublitz","Charlotte Byrde"), CM("Julia Garner","Ruth Langmore"), CM("Tom Pelphrey","Ben Davis")],
                trailerUrl: "5hAXVqrljbs"),

            CatalogSeries( "Narcos", 2015, 8.8,
                ["Biography", "Crime", "Drama"],
                $"{TmdbBase}/rTmal9fDbwh5F0waol2hq35U4ah.jpg",
                "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through much of the 1970s, 80s and 90s.", 30,
                backdrop: null,
                director: "Carlo Bernard & Chris Brancato",
                writers: ["Carlo Bernard", "Chris Brancato", "Doug Miro"],
                studio: "Netflix",
                cast: [CM("Wagner Moura","Pablo Escobar"), CM("Boyd Holbrook","Steve Murphy"), CM("Pedro Pascal","Javier Peña"), CM("Joanna Christie","Connie Murphy"), CM("Juan Pablo Raba","Roberto Escobar")],
                trailerUrl: "xl8zdCY-abw"),

            CatalogSeries( "The Crown", 2016, 8.6,
                ["Biography", "Drama", "History"],
                $"{TmdbBase}/1M876KPjulVwppEpldhdc8V4o68.jpg",
                "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.", 60,
                backdrop: null,
                director: "Peter Morgan",
                writers: ["Peter Morgan"],
                studio: "Netflix",
                cast: [CM("Claire Foy","Queen Elizabeth II, S1-2"), CM("Olivia Colman","Queen Elizabeth II, S3-4"), CM("Matt Smith","Prince Philip, S1-2"), CM("Tobias Menzies","Prince Philip, S3-4"), CM("Vanessa Kirby","Princess Margaret, S1-2")],
                trailerUrl: "JWtnJjn6ng0"),

            CatalogSeries( "The Mandalorian", 2019, 8.7,
                ["Action", "Adventure", "Sci-Fi"],
                $"{TmdbBase}/sWgBv7LV2rencCJ56KkjqBdB4z8.jpg",
                "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic.", 24,
                backdrop: null,
                director: "Jon Favreau",
                writers: ["Jon Favreau"],
                studio: "Disney+",
                cast: [CM("Pedro Pascal","Din Djarin / The Mandalorian"), CM("Giancarlo Esposito","Moff Gideon"), CM("Carl Weathers","Greef Karga"), CM("Gina Carano","Cara Dune"), CM("Nick Nolte","Kuiil")],
                trailerUrl: "aOC8E8z_ifw"),

            CatalogSeries( "Fargo", 2014, 9.0,
                ["Comedy", "Crime", "Drama"],
                $"{TmdbBase}/gLMuKFE6A9GQs4xVCJnW7aEqT4j.jpg",
                "Various chronicles of deception, intrigue and murder in and around frozen Minnesota. Yet all of these tales mysteriously lead back to one another.", 53,
                backdrop: null,
                director: "Noah Hawley",
                writers: ["Noah Hawley"],
                studio: "FX",
                cast: [CM("Billy Bob Thornton","Lorne Malvo (S1)"), CM("Martin Freeman","Lester Nygaard (S1)"), CM("Kirsten Dunst","Peggy Blomquist (S2)"), CM("Ewan McGregor","Emmit / Ray Stussy (S3)"), CM("Allison Tolman","Molly Solverson (S1)")],
                trailerUrl: "wHPSWMYBFNE"),

            CatalogSeries( "Barry", 2018, 8.4,
                ["Comedy", "Crime", "Drama"],
                $"{TmdbBase}/nY9yFR9BcrBPGkVTHJtaaDJVt12.jpg",
                "A hitman from the Midwest moves to Los Angeles and tries to pursue a career in acting, while maintaining his criminal underworld connections.", 32,
                backdrop: null,
                director: "Alec Berg & Bill Hader",
                writers: ["Alec Berg", "Bill Hader"],
                studio: "HBO",
                cast: [CM("Bill Hader","Barry Berkman / Barry Block"), CM("Stephen Root","Monroe Fuches"), CM("Sarah Goldberg","Sally Reed"), CM("Henry Winkler","Gene Cousineau"), CM("Anthony Carrigan","NoHo Hank")],
                trailerUrl: "7hM3dJJekKQ"),

            CatalogSeries( "Yellowstone", 2018, 8.7,
                ["Drama", "Western"],
                $"{TmdbBase}/6CIh1UMWiOMHkHLlXh4SClxSWUH.jpg",
                "A ranching family in Montana fights off real estate developers, an Indian reservation, and other forces that seek to take their land.", 50,
                backdrop: null,
                director: "Taylor Sheridan",
                writers: ["Taylor Sheridan", "John Linson"],
                studio: "Paramount Network",
                cast: [CM("Kevin Costner","John Dutton"), CM("Luke Grimes","Kayce Dutton"), CM("Kelly Reilly","Beth Dutton"), CM("Wes Bentley","Jamie Dutton"), CM("Cole Hauser","Rip Wheeler")],
                trailerUrl: "UKolpSACQSA"),

            CatalogSeries( "Ted Lasso", 2020, 8.8,
                ["Comedy", "Drama", "Sport"],
                $"{TmdbBase}/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg",
                "American college football coach Ted Lasso is hired to manage AFC Richmond, an English soccer team, despite having no experience managing the sport.", 34,
                backdrop: null,
                director: "Jason Sudeikis",
                writers: ["Jason Sudeikis", "Bill Lawrence", "Brendan Hunt", "Joe Kelly"],
                studio: "Apple TV+",
                cast: [CM("Jason Sudeikis","Ted Lasso"), CM("Hannah Waddingham","Rebecca Welton"), CM("Brett Goldstein","Roy Kent"), CM("Juno Temple","Keeley Jones"), CM("Phil Dunster","Jamie Tartt")],
                trailerUrl: "cFHCcYT2cMQ"),
        });

        // ─────────────────────────────────────────
        // ANIME (posters via Jikan/MyAnimeList)
        // ─────────────────────────────────────────
        var animeItems = await BuildAnimeCatalogAsync();
        list.AddRange(animeItems);

        // Remove duplicados por título (case-insensitive)
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        return list.Where(x =>
        {
            if (seen.Contains(x.Title)) return false;
            seen.Add(x.Title);
            return true;
        }).ToList();
    }

    private sealed record AnimeSeedData(string Title, int Year, double Rating, List<string> Genres, string Synopsis, int Eps, string Director, List<string> Writers, string Studio, List<CastMember> Cast, string TrailerId);

    private async Task<List<CatalogItem>> BuildAnimeCatalogAsync()
    {
        var fallbackPoster = "https://via.placeholder.com/500x750/1a1a2e/eee?text=Anime";
        var items = new List<CatalogItem>();

        var animeData = new AnimeSeedData[]
        {
            new("Attack on Titan", 2013, 9.0, ["Action", "Dark Fantasy", "Drama"], "Humanity fights for survival against giant humanoid Titans that have forced them to live within enormous walled cities.", 87, "Tetsuro Araki", ["Yasuko Kobayashi"], "Wit Studio / MAPPA", [CM("Yuki Kaji","Eren Yeager (JP)"), CM("Bryce Papenbrook","Eren Yeager (EN)"), CM("Yui Ishikawa","Mikasa Ackerman (JP)"), CM("Josh Grelle","Armin Arlert (EN)"), CM("Kishō Taniyama","Jean Kirstein (JP)")], "MGRm4IzK1SQ"),
            new("Fullmetal Alchemist: Brotherhood", 2009, 9.1, ["Action", "Adventure", "Fantasy"], "Two brothers search for a Philosopher's Stone after an attempt to revive their deceased mother goes wrong.", 64, "Yasuhiro Irie", ["Hiroshi Ōnogi"], "Bones", [CM("Romi Park","Edward Elric (JP)"), CM("Vic Mignogna","Edward Elric (EN)"), CM("Rie Kugimiya","Alphonse Elric (JP)"), CM("Maxey Whitehead","Alphonse Elric (EN)")], "--IcmZkvL0Q"),
            new("Death Note", 2006, 9.0, ["Mystery", "Psychological", "Thriller"], "A high school student discovers a supernatural notebook that grants its user the ability to kill anyone whose name is written in it.", 37, "Tetsuro Araki", ["Toshiki Inoue"], "Madhouse", [CM("Mamoru Miyano","Light Yagami (JP)"), CM("Brad Swaile","Light Yagami (EN)"), CM("Kappei Yamaguchi","L (JP)"), CM("Alessandro Juliani","L (EN)"), CM("Aya Hirano","Misa Amane (JP)")], "xbM_GFWLIhQ"),
            new("Demon Slayer", 2019, 8.7, ["Action", "Fantasy"], "A young man becomes a demon slayer after his family is slaughtered and his younger sister is turned into a demon.", 55, "Haruo Sotozaki", ["Ufotable"], "ufotable", [CM("Natsuki Hanae","Tanjiro Kamado (JP)"), CM("Zach Aguilar","Tanjiro Kamado (EN)"), CM("Akari Kitō","Nezuko Kamado (JP)"), CM("Yoshitsugu Matsuoka","Zenitsu Agatsuma (JP)")], "VQGCKyvzIM4"),
            new("Hunter x Hunter", 2011, 9.0, ["Action", "Adventure", "Fantasy"], "A young boy sets out to become a Hunter, an elite member of humanity's best.", 148, "Hiroshi Kōjina", ["Atsushi Maekawa"], "Madhouse", [CM("Megumi Han","Gon Freecss (JP)"), CM("Erica Mendez","Gon Freecss (EN)"), CM("Mariya Ise","Killua Zoldyck (JP)"), CM("Cristina Vee","Killua Zoldyck (EN)"), CM("Daisuke Namikawa","Hisoka (JP)")], "D9iTQFOe6rE"),
            new("My Hero Academia", 2016, 8.4, ["Action", "Comedy", "Sci-Fi"], "A superhero-loving boy without any powers is determined to enroll in a prestigious hero academy.", 138, "Kenji Nagasaki", ["Yōsuke Kuroda"], "Bones", [CM("Daiki Yamashita","Izuku Midoriya (JP)"), CM("Justin Briner","Izuku Midoriya (EN)"), CM("Kenta Miyake","All Might (JP)"), CM("Christopher Sabat","All Might (EN)"), CM("Nobuhiko Okamoto","Katsuki Bakugo (JP)")], "D98KeBAuxMc"),
            new("Steins;Gate", 2011, 9.1, ["Drama", "Sci-Fi", "Thriller"], "A group of lab members accidentally invent time travel and must use their discovery to prevent worldwide disasters.", 24, "Hiroshi Hamasaki", ["Jukki Hanada"], "White Fox", [CM("Mamoru Miyano","Rintarō Okabe (JP)"), CM("J. Michael Tatum","Rintarō Okabe (EN)"), CM("Kana Hanazawa","Mayuri Shiina (JP)"), CM("Asami Imai","Kurisu Makise (JP)"), CM("Lindsay Seidel","Kurisu Makise (EN)")], "27OZc-ku6is"),
            new("Code Geass", 2006, 8.7, ["Action", "Drama", "Mecha"], "A prince of the fallen nation fights against the Holy Britannian Empire using military strategy and the power of absolute obedience.", 50, "Gorō Taniguchi", ["Ichirō Ōkouchi"], "Sunrise", [CM("Jun Fukuyama","Lelouch Lamperouge (JP)"), CM("Johnny Yong Bosch","Lelouch Lamperouge (EN)"), CM("Yukana","C.C. (JP)"), CM("Kate Higgins","C.C. (EN)"), CM("Takahiro Sakurai","Suzaku Kururugi (JP)")], "rSv44qc2pL8"),
            new("One Punch Man", 2015, 8.8, ["Action", "Comedy", "Sci-Fi"], "The story of Saitama, a hero who can defeat any enemy with a single punch but seeks to find a worthy opponent.", 24, "Shingo Natsume", ["Tomohiro Suzuki"], "Madhouse", [CM("Makoto Furukawa","Saitama (JP)"), CM("Max Mittelman","Saitama (EN)"), CM("Kaito Ishikawa","Genos (JP)"), CM("Zach Aguilar","Genos (EN)")], "qnGiPkHVr98"),
            new("Neon Genesis Evangelion", 1995, 8.5, ["Action", "Drama", "Mecha"], "A teenager is recruited into the shadowy organization NERV to pilot giant mechas against mysterious beings known as Angels.", 26, "Hideaki Anno", ["Hideaki Anno"], "Gainax", [CM("Megumi Ogata","Shinji Ikari (JP)"), CM("Spike Spencer","Shinji Ikari (EN)"), CM("Kotono Mitsuishi","Misato Katsuragi (JP)"), CM("Allison Keith","Misato Katsuragi (EN)"), CM("Yūko Miyamura","Asuka Langley Soryu (JP)")], "7DtQUdGIMqY"),
            new("Vinland Saga", 2019, 8.8, ["Action", "Adventure", "Drama"], "Thorfinn pursues a journey with his father's killer in order to take revenge on his father's death.", 48, "Shuhei Yabuta", ["Hiroshi Seko"], "Wit Studio", [CM("Yuto Uemura","Thorfinn (JP)"), CM("Naoya Uchida","Askeladd (JP)"), CM("Takehito Koyasu","Floki (JP)"), CM("Hiroki Yasumoto","Thorkell (JP)")], "JbJFzh_XzZ4"),
            new("Jujutsu Kaisen", 2020, 8.6, ["Action", "Fantasy", "Supernatural"], "A boy swallows a cursed talisman — the finger of a demon — and becomes part of it. He enters a shaman college to locate the demon's other body parts.", 47, "Sunghoo Park", ["Hiroshi Seko"], "MAPPA", [CM("Junya Enoki","Yuji Itadori (JP)"), CM("Adam McArthur","Yuji Itadori (EN)"), CM("Yūichi Nakamura","Satoru Gojo (JP)"), CM("Kaiji Tang","Satoru Gojo (EN)"), CM("Asami Seto","Nobara Kugisaki (JP)")], "pkKu9hLT-t8"),
            new("Spy x Family", 2022, 8.5, ["Action", "Comedy", "Spy"], "A spy must build a fake family to complete a mission, not realizing that the girl he adopts is a telepath and his wife is an assassin.", 37, "Kazuhiro Furuhashi", ["Ichirō Ōkouchi"], "Wit Studio / CloverWorks", [CM("Takuya Eguchi","Loid Forger (JP)"), CM("Saori Hayami","Yor Forger (JP)"), CM("Atsumi Tanezaki","Anya Forger (JP)"), CM("Alex Organ","Loid Forger (EN)"), CM("Natalie Van Sistine","Yor Forger (EN)")], "ZzGd4JVWMrM"),
            new("Chainsaw Man", 2022, 8.5, ["Action", "Dark Fantasy", "Horror"], "Denji is a teenage boy living with a Chainsaw Devil named Pochita. Due to the debt his father left behind, he has been living a rock-bottom life.", 12, "Ryū Nakayama", ["Hiroshi Seko"], "MAPPA", [CM("Kikunosuke Toya","Denji (JP)"), CM("Ryan Colt Levy","Denji (EN)"), CM("Tomori Kusunoki","Power (JP)"), CM("Sarah Wiedenheft","Power (EN)"), CM("Mariya Ise","Makima (JP)")], "q6kJbONnOvE"),
            new("Cowboy Bebop", 1998, 8.9, ["Action", "Adventure", "Sci-Fi"], "The adventures of an easygoing bounty hunter and his partners, set in the year 2071.", 26, "Shinichirō Watanabe", ["Keiko Nobumoto"], "Sunrise", [CM("Kōichi Yamadera","Spike Spiegel (JP)"), CM("Steve Blum","Spike Spiegel (EN)"), CM("Unsho Ishizuka","Jet Black (JP)"), CM("Beau Billingslea","Jet Black (EN)"), CM("Megumi Hayashibara","Faye Valentine (JP)")], "gn1kI5V2e7s"),
            new("Naruto: Shippuden", 2007, 8.7, ["Action", "Adventure", "Fantasy"], "Naruto Uzumaki returns after two years of training to fight against the evil Akatsuki organization.", 500, "Hayato Date", ["Junki Takegami"], "Pierrot", [CM("Junko Takeuchi","Naruto Uzumaki (JP)"), CM("Maile Flanagan","Naruto Uzumaki (EN)"), CM("Chie Nakamura","Sakura Haruno (JP)"), CM("Kate Higgins","Sakura Haruno (EN)"), CM("Noriaki Sugiyama","Sasuke Uchiha (JP)")], "vBUh4V7d7jU"),
            new("Dragon Ball Z", 1989, 8.8, ["Action", "Adventure", "Fantasy"], "After learning that he is from another planet, a warrior named Goku and his friends defend it from an onslaught of extraterrestrial enemies.", 291, "Daisuke Nishio", ["Takao Koyama"], "Toei Animation", [CM("Masako Nozawa","Son Goku (JP)"), CM("Sean Schemmel","Son Goku (EN)"), CM("Ryō Horikawa","Vegeta (JP)"), CM("Christopher Sabat","Vegeta (EN)"), CM("Takeshi Kusao","Trunks (JP)")], "EZx3E5ZHUbk"),
            new("One Piece", 1999, 8.9, ["Action", "Adventure", "Fantasy"], "Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger.", 1100, "Konosuke Uda", ["Shōji Yonemura"], "Toei Animation", [CM("Mayumi Tanaka","Monkey D. Luffy (JP)"), CM("Colleen Clinkenbeard","Monkey D. Luffy (EN)"), CM("Kazuya Nakai","Roronoa Zoro (JP)"), CM("Christopher Sabat","Roronoa Zoro (EN)"), CM("Akemi Okamura","Nami (JP)")], "S8_YwFLCh4U"),
            new("Sword Art Online", 2012, 7.4, ["Action", "Adventure", "Fantasy"], "A boy is trapped in a virtual reality MMORPG, where death in-game means death in real life.", 96, "Tomohiko Itō", ["Yukito Kizawa"], "A-1 Pictures", [CM("Yoshitsugu Matsuoka","Kirito (JP)"), CM("Bryce Papenbrook","Kirito (EN)"), CM("Haruka Tomatsu","Asuna (JP)"), CM("Cherami Leigh","Asuna (EN)"), CM("Kanae Itō","Silica (JP)")], "6ohYYtxfDCg"),
            new("Tokyo Ghoul", 2014, 7.9, ["Action", "Dark Fantasy", "Horror"], "A Tokyo college student is attacked by a ghoul and becomes a half-ghoul himself.", 48, "Shuhei Morita", ["Chuuji Mikasano"], "Pierrot", [CM("Natsuki Hanae","Ken Kaneki (JP)"), CM("Austin Tindle","Ken Kaneki (EN)"), CM("Sora Amamiya","Touka Kirishima (JP)"), CM("Monica Rial","Touka Kirishima (EN)"), CM("Yuichi Nakamura","Uta (JP)")], "j4CdGX1Gi0Y"),
            new("Mob Psycho 100", 2016, 8.5, ["Action", "Comedy", "Supernatural"], "A psychic middle school boy tries to live a normal life and avoid using his powers, but extraordinary events keep drawing him back.", 37, "Yuzuru Tachikawa", ["Hiroshi Seko"], "Bones", [CM("Setsuo Ito","Shigeo 'Mob' Kageyama (JP)"), CM("Kyle McCarley","Mob (EN)"), CM("Takahiro Sakurai","Reigen Arataka (JP)"), CM("Chris Niosi","Reigen (EN)")], "VqbfzFaWkuY"),
            new("Re:Zero − Starting Life in Another World", 2016, 8.2, ["Dark Fantasy", "Isekai"], "Subaru Natsuki is suddenly transported to another world and discovers he has the power to return from death.", 50, "Masaharu Watanabe", ["Masahiro Yokotani"], "White Fox", [CM("Yūsuke Kobayashi","Subaru Natsuki (JP)"), CM("Sean Chiplock","Subaru (EN)"), CM("Rie Takahashi","Rem (JP)"), CM("Inori Minase","Emilia (JP)"), CM("Chinatsu Akasaki","Beatrice (JP)")], "R47GvhFkHoE"),
            new("Violet Evergarden", 2018, 8.5, ["Drama", "Fantasy"], "In the aftermath of a great war, Violet Evergarden, a young soldier, begins work as a letter writer to understand the meaning of the last words her mentor said to her.", 13, "Taichi Ishidate", ["Reiko Yoshida"], "Kyoto Animation", [CM("Yui Ishikawa","Violet Evergarden (JP)"), CM("Daisuke Namikawa","Gilbert Bougainvillea (JP)"), CM("Takehito Koyasu","Claudia Hodgins (JP)"), CM("Aya Endō","Cattleya Baudelaire (JP)")], "0CJeDetA45Q"),
            new("Made in Abyss", 2017, 8.7, ["Adventure", "Dark Fantasy", "Sci-Fi"], "In a world with a huge chasm stretching down into the Earth called the Abyss, a 12-year-old girl descends to search for her missing mother.", 25, "Masayuki Kojima", ["Hideyuki Kurata"], "Kinema Citrus", [CM("Miyu Tomita","Riko (JP)"), CM("Mariya Ise","Reg (JP)"), CM("Shiori Izawa","Nanachi (JP)"), CM("Eri Kitamura","Ozen (JP)")], "FHXnXKGJXiM"),
            new("Parasyte: The Maxim", 2014, 8.3, ["Action", "Horror", "Sci-Fi"], "Parasitic aliens have invaded Earth and Shinichi Izumi falls victim to one, but his Parasyte fails to take over his brain and only takes over his right arm.", 24, "Kenichi Shimizu", ["Shoji Yonemura"], "Madhouse", [CM("Nobunaga Shimazaki","Shinichi Izumi (JP)"), CM("Adam Gibbs","Shinichi (EN)"), CM("Aya Hirano","Satomi Murano (JP)"), CM("Kana Hanazawa","Kana Kimishima (JP)")], "bHBBVKi3AhE"),
            new("Haikyuu!!", 2014, 8.7, ["Comedy", "Drama", "Sport"], "Inspired after watching a volleyball ace nicknamed 'Little Giant', Shoyo Hinata joins his high school volleyball club and works his way to the top despite his short stature.", 85, "Susumu Mitsunaka", ["Taku Kishimoto"], "Production I.G", [CM("Ayumu Murase","Shōyō Hinata (JP)"), CM("Kaito Ishikawa","Tobio Kageyama (JP)"), CM("Kōki Uchiyama","Kei Tsukishima (JP)"), CM("Yu Hayashi","Ryūnosuke Tanaka (JP)"), CM("Yoshimasa Hosoya","Asahi Azumane (JP)")], "nyGuOKEUhGs"),
            new("Your Lie in April", 2014, 8.6, ["Drama", "Music", "Romance"], "A piano prodigy who lost his ability to hear the sound of his own playing is drawn back to music by a free-spirited violinist.", 22, "Kyōhei Ishiguro", ["Takao Yoshioka"], "A-1 Pictures", [CM("Natsuki Hanae","Kōsei Arima (JP)"), CM("Risa Taneda","Kaori Miyazono (JP)"), CM("Ayane Sakura","Tsubaki Sawabe (JP)"), CM("Ryōta Ōsaka","Ryōta Watari (JP)")], "U7NWZKKlIuE"),
            new("Mushoku Tensei: Jobless Reincarnation", 2021, 8.3, ["Adventure", "Drama", "Fantasy"], "A 34-year-old shut-in is reincarnated into a fantasy world as a baby and resolves to live his new life to the fullest.", 23, "Manabu Okamoto", ["Manabu Okamoto"], "Bind", [CM("Yūma Uchida","Rudeus Greyrat (JP)"), CM("Matthew David Rudd","Rudeus (EN)"), CM("Ai Kayano","Zenith Greyrat (JP)"), CM("Tomori Kusunoki","Sylphiette (JP)")], "PxVBxFSpkyI"),
            new("Overlord", 2015, 7.9, ["Action", "Adventure", "Fantasy"], "When a popular virtual reality game is scheduled to shut down, a player decides to stay logged in until the end but finds himself trapped in a new world as his game character.", 52, "Naoyuki Itou", ["Yukie Sugawara"], "Madhouse", [CM("Satoshi Hino","Ainz Ooal Gown (JP)"), CM("Chris Guerrero","Ainz (EN)"), CM("Yumi Hara","Albedo (JP)"), CM("Sumire Uesaka","Shalltear Bloodfallen (JP)")], "BlASGYvbFsU"),
            new("Frieren: Beyond Journey's End", 2023, 9.0, ["Adventure", "Fantasy"], "After the party of heroes that defeated the Demon King disbanded, the elven mage Frieren embarks on a journey to learn more about humanity.", 28, "Keiichiro Saitō", ["Tomohiro Suzuki"], "Madhouse", [CM("Atsumi Tanezaki","Frieren (JP)"), CM("Konomi Kohara","Fern (JP)"), CM("Chiaki Kobayashi","Stark (JP)"), CM("Yōji Ueda","Himmel (JP)"), CM("Hinata Tadokoro","Sein (JP)")], "2nVhzMDFk_g"),
        };

        foreach (var a in animeData)
        {
            var poster = AnimeMalIds.TryGetValue(a.Title, out var malId)
                ? await _jikan.GetPosterUrlAsync(malId) ?? fallbackPoster
                : fallbackPoster;
            await Task.Delay(400); // Rate limit Jikan: ~3 req/s
            items.Add(CatalogAnime(a.Title, a.Year, a.Rating, a.Genres, poster, a.Synopsis, a.Eps,
                backdrop: null, director: a.Director, writers: a.Writers, studio: a.Studio, cast: a.Cast, trailerUrl: a.TrailerId));
        }

        return items;
    }

    // ─── Helpers ───────────────────────────────
    private static CastMember CM(string name, string? character = null, string? photoUrl = null) => new()
    {
        Name = name,
        Character = character,
        PhotoUrl = photoUrl,
    };

    private static CatalogItem CatalogMovie(string title, int year, double rating,
        List<string> genres, string poster, string synopsis, int durationMinutes,
        string? backdrop = null, string? director = null, List<string>? writers = null,
        string? studio = null, List<CastMember>? cast = null, string? trailerUrl = null) => new()
    {
        Title = title,
        Type = MediaType.Movie,
        Year = year,
        Rating = rating,
        Genres = genres,
        PosterUrl = poster,
        BackdropUrl = backdrop,
        Synopsis = synopsis,
        DurationMinutes = durationMinutes,
        Director = director,
        Writers = writers ?? [],
        Studio = studio,
        Cast = cast ?? [],
        TrailerUrl = trailerUrl,
    };

    private static CatalogItem CatalogSeries(string title, int year, double rating,
        List<string> genres, string poster, string synopsis, int totalEpisodes,
        string? backdrop = null, string? director = null, List<string>? writers = null,
        string? studio = null, List<CastMember>? cast = null, string? trailerUrl = null) => new()
    {
        Title = title,
        Type = MediaType.Series,
        Year = year,
        Rating = rating,
        Genres = genres,
        PosterUrl = poster,
        BackdropUrl = backdrop,
        Synopsis = synopsis,
        TotalEpisodes = totalEpisodes,
        Director = director,
        Writers = writers ?? [],
        Studio = studio,
        Cast = cast ?? [],
        TrailerUrl = trailerUrl,
    };

    private static CatalogItem CatalogAnime(string title, int year, double rating,
        List<string> genres, string poster, string synopsis, int totalEpisodes,
        string? backdrop = null, string? director = null, List<string>? writers = null,
        string? studio = null, List<CastMember>? cast = null, string? trailerUrl = null) => new()
    {
        Title = title,
        Type = MediaType.Anime,
        Year = year,
        Rating = rating,
        Genres = genres,
        PosterUrl = poster,
        BackdropUrl = backdrop,
        Synopsis = synopsis,
        TotalEpisodes = totalEpisodes,
        Director = director,
        Writers = writers ?? [],
        Studio = studio,
        Cast = cast ?? [],
        TrailerUrl = trailerUrl,
    };
}
